# Generated by Django 5.2.5 on 2025-09-20 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricSharingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text="pl. 'biometric_data'", max_length=100, verbose_name='Alkalmazás neve')),
                ('table_name', models.CharField(help_text="pl. 'WeightData'", max_length=100, verbose_name='Tábla neve')),
                ('enabled', models.BooleanField(default=False, help_text='Be van-e kapcsolva a megosztás', verbose_name='Engedélyezve')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás időpontja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Utolsó módosítás időpontja')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Adatokat fogadó felhasználó')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Adatokat megosztó felhasználó')),
            ],
            options={
                'verbose_name': 'Biometriai adat megosztási engedély',
                'verbose_name_plural': 'Biometriai adat megosztási engedélyek',
                'ordering': ['-updated_at', 'app_name', 'table_name'],
                'indexes': [models.Index(fields=['user', 'enabled'], name='data_sharin_user_id_8b5d3d_idx'), models.Index(fields=['target_user', 'enabled'], name='data_sharin_target__fbcb9b_idx'), models.Index(fields=['app_name', 'table_name'], name='data_sharin_app_nam_431dd2_idx')],
                'unique_together': {('user', 'target_user', 'app_name', 'table_name')},
            },
        ),
    ]
