# Generated by Django 5.2.5 on 2026-01-30 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricsharingpermission',
            name='shared_by',
            field=models.ForeignKey(help_text='Kiskorú esetén a szülő, nagykorú esetén a sportoló.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_created', to=settings.AUTH_USER_MODEL, verbose_name='Ki adta az engedélyt?'),
        ),
    ]
