# Generated by Django 5.2.5 on 2026-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sharing', '0002_biometricsharingpermission_shared_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricsharingpermission',
            name='shared_by',
        ),
        migrations.AddField(
            model_name='biometricsharingpermission',
            name='athlete_consent',
            field=models.BooleanField(default=False, verbose_name='Sportoló beleegyezése'),
        ),
        migrations.AddField(
            model_name='biometricsharingpermission',
            name='parent_consent',
            field=models.BooleanField(default=False, verbose_name='Szülői jóváhagyás'),
        ),
    ]
