# Generated by Django 5.2.5 on 2026-02-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sharing', '0003_remove_biometricsharingpermission_shared_by_and_more'),
        ('users', '0005_sport_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSharingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('athlete_consent', models.BooleanField(default=False)),
                ('parent_consent', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_given', to=settings.AUTH_USER_MODEL)),
                ('target_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_received', to=settings.AUTH_USER_MODEL)),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrole')),
            ],
            options={
                'verbose_name': 'Adatmegosztási engedély',
                'verbose_name_plural': 'Adatmegosztási engedélyek',
                'unique_together': {('athlete', 'target_person', 'target_role', 'app_name', 'table_name')},
            },
        ),
        migrations.DeleteModel(
            name='BiometricSharingPermission',
        ),
    ]
