# Generated by Django 5.2.5 on 2025-09-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrole',
            name='approved_by_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='approved_by_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='A sportoló szülője (ha kiskorú)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentchild_parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentchild_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Ki hagyta véglegesen jóvá ezt a szerepkört', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='coach',
            field=models.ForeignKey(blank=True, help_text='A sportoló vagy szülőhöz rendelt edző', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'club', 'sport', 'coach', 'parent')},
        ),
    ]
