# Generated by Django 5.2.5 on 2026-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251017_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('COMBAT', 'Küzdősport (Birkózás, Judo, Vívás)'), ('TEAM', 'Csapatsport (Foci, Kézi, Vízilabda, Kosár)'), ('ENDURANCE', 'Állóképességi (Futás, Úszás, Kerékpár)'), ('POWER_TECH', 'Erő/Technikai (Súlylökés, Fitness, Dobóatlétika)')], default='TEAM', max_length=20),
        ),
    ]
