# Generated by Django 5.2.5 on 2025-10-12 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=255, unique=True, verbose_name='Algoritmus neve')),
                ('cost_per_run', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Költség (Credit)')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
            ],
            options={
                'verbose_name': 'Algoritmus Ár',
                'verbose_name_plural': 'Algoritmus Árak',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Csomag neve')),
                ('price_ft', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ár (Ft/ciklus)')),
                ('duration_days', models.IntegerField(verbose_name='Időtartam (nap)')),
                ('is_ad_free', models.BooleanField(default=False, verbose_name='Hirdetésmentes funkció')),
            ],
            options={
                'verbose_name': 'Előfizetési Csomag',
                'verbose_name_plural': 'Előfizetési Csomagok',
            },
        ),
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ft', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Feltöltendő összeg (Ft)')),
                ('billing_name', models.CharField(max_length=255, verbose_name='Számlázási Név')),
                ('billing_address', models.TextField(verbose_name='Számlázási Cím')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adószám')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Igénylés dátuma')),
                ('status', models.CharField(choices=[('PENDING', 'Függőben'), ('SENT', 'Elküldve'), ('CANCELLED', 'Törölve')], default='PENDING', max_length=10, verbose_name='Státusz')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_target_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Cél felhasználó (aki kapja a Creditet)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Igénylő felhasználó')),
            ],
            options={
                'verbose_name': 'Számlaigénylés',
                'verbose_name_plural': 'Számlaigénylések',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOP_UP', 'Credit Feltöltés (Ft-ból)'), ('ALGO_RUN', 'Algoritmus Futtatás'), ('AD_EARN', 'Hirdetésnézésből szerzett Credit'), ('SUB_PAY', 'Előfizetés fizetés'), ('TRANSFER', 'Egyenleg átutalás')], max_length=10, verbose_name='Típus')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Összeg (Credit)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Időpont')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_related', to=settings.AUTH_USER_MODEL, verbose_name='Kapcsolódó felhasználó (pl. fizető/cél)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_affected', to=settings.AUTH_USER_MODEL, verbose_name='Érintett felhasználó (Credit tulajdonosa)')),
            ],
            options={
                'verbose_name': 'Tranzakció',
                'verbose_name_plural': 'Tranzakciók',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Credit Egyenleg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Credit Egyenleg',
                'verbose_name_plural': 'Credit Egyenlegek',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kezdés dátuma')),
                ('end_date', models.DateTimeField(verbose_name='Lejárat dátuma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan', verbose_name='Csomag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Felhasználói Előfizetés',
                'verbose_name_plural': 'Felhasználói Előfizetések',
            },
        ),
    ]
