# Generated by Django 5.2.5 on 2026-01-05 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Csomag neve')),
                ('plan_type', models.CharField(choices=[('AD_FREE', 'Hirdetésmentesség (Időalapú)'), ('ML_ACCESS', 'ML Funkciók (Időalapú)'), ('ANALYSIS_PACK', 'Elemzési Csomag (Darabszám alapú)')], max_length=20, verbose_name='Típus')),
                ('price_ft', models.PositiveIntegerField(verbose_name='Ár (Ft)')),
                ('price_in_credits', models.PositiveIntegerField(verbose_name='Ár (Kreditben)')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Időtartam (nap)')),
                ('analysis_count', models.PositiveIntegerField(default=0, verbose_name='Elemzések száma (db)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív?')),
            ],
            options={
                'verbose_name': 'Szolgáltatási Csomag',
                'verbose_name_plural': 'Szolgáltatási Csomagok',
            },
        ),
        migrations.CreateModel(
            name='TopUpInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Igényelve (Várakozik)'), ('INVOICED', 'Számla kiküldve'), ('APPROVED', 'Fizetve / Jóváhagyva'), ('REJECTED', 'Elutasítva')], default='PENDING', max_length=15)),
                ('amount_ft', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Összeg (Ft)')),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_address', models.TextField()),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.serviceplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalysisBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Elemzési keret (db)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='Kreditek')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('ML_ACCESS', 'ML'), ('AD_FREE', 'Hirdetésmentesség')], max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
