# Generated by Django 5.2.5 on 2026-01-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Szerzés (Hirdetés/Bónusz)'), ('SPEND', 'Levonás (Vásárlás/Beváltás)'), ('ADMIN', 'Adminisztrátori módosítás')], max_length=10)),
                ('amount', models.IntegerField(help_text='Pozitív ha kap, negatív ha költ')),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pénzügyi Tranzakció',
                'verbose_name_plural': 'Pénzügyi Tranzakciók',
                'ordering': ['-timestamp'],
            },
        ),
    ]
