# Generated by Django 5.2.5 on 2026-01-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_financialtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='price_ft',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ár (Ft)'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='price_in_credits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ár (Kreditben)'),
        ),
    ]
