# Generated by Django 5.2.5 on 2025-10-18 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_transactionhistory_is_pending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerequest',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_target_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Jóváírás Személye'),
        ),
    ]
