# Generated by Django 5.2.5 on 2026-01-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_serviceplan_price_ft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Leírás'),
        ),
    ]
