# Generated by Django 5.2.5 on 2025-11-13 12:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoicerequest_target_user'),
        ('diagnostics_jobs', '0020_diagnosticjob_billing_transaction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ft', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Összeg (Ft)')),
                ('transaction_type', models.CharField(choices=[('TOPUP', 'Feltöltés számla alapján (Bevétel)'), ('DIAGNOSTICS_RUN', 'Diagnosztikai futtatás (Kiadás)'), ('ML_PREDICTION', 'ML Előrejelzés (Kiadás)'), ('ADMIN_ADJUSTMENT', 'Adminisztrátori korrekció')], max_length=50, verbose_name='Típus')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Időpont')),
                ('is_consumption', models.BooleanField(default=False, verbose_name='Fogyasztás/Kiadás-e')),
                ('transaction_status', models.CharField(choices=[('COMPLETED', 'Befejezett'), ('PENDING', 'Függőben (Foglalás)'), ('REFUNDED', 'Visszatérítve'), ('FAILED', 'Sikertelen')], default='COMPLETED', max_length=10, verbose_name='Tranzakció Státusz')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Megjegyzés')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics_jobs.diagnosticjob', verbose_name='Kapcsolódó Job')),
            ],
            options={
                'verbose_name': 'Pénzügyi Tranzakció',
                'verbose_name_plural': 'Pénzügyi Tranzakciók',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('GENERAL', 'Általános (Régi)'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('SQUAT_ASSESSMENT', 'Guggolás Biomechanikai Elemzés'), ('POSTURE_ASSESSMENT', 'Testtartás Statikus/Dinamikus Elemzés'), ('ANTHROPOMETRY_CALIBRATION', 'Antropometria Kalibráció Két Képpel'), ('SHOULDER_CIRCUMDUCTION', 'Vállkörzés elemzés'), ('VERTICAL_JUMP', 'Helyből Magassági Ugrás Elemzés'), ('SINGLE_LEG_STANCE_LEFT', 'Egylábon Állás (Bal)'), ('SINGLE_LEG_STANCE_RIGHT', 'Egylábon Állás (Jobb)')], max_length=50, unique=True, verbose_name='Feladat Típus')),
                ('base_price_ft', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alap Ár (Ft)')),
            ],
            options={
                'verbose_name': 'Feladat Alapár',
                'verbose_name_plural': 'Feladat Alapárak',
            },
        ),
        migrations.CreateModel(
            name='UserJobDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('GENERAL', 'Általános (Régi)'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('SQUAT_ASSESSMENT', 'Guggolás Biomechanikai Elemzés'), ('POSTURE_ASSESSMENT', 'Testtartás Statikus/Dinamikus Elemzés'), ('ANTHROPOMETRY_CALIBRATION', 'Antropometria Kalibráció Két Képpel'), ('SHOULDER_CIRCUMDUCTION', 'Vállkörzés elemzés'), ('VERTICAL_JUMP', 'Helyből Magassági Ugrás Elemzés'), ('SINGLE_LEG_STANCE_LEFT', 'Egylábon Állás (Bal)'), ('SINGLE_LEG_STANCE_RIGHT', 'Egylábon Állás (Jobb)')], max_length=50, verbose_name='Feladat Típus, amire a kedvezmény vonatkozik')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kedvezmény (%)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Feladat Kedvezmény',
                'verbose_name_plural': 'Feladat Kedvezmények',
                'unique_together': {('user', 'job_type')},
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_ft', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Aktuális egyenleg (Ft)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Felhasználói Pénztárca',
                'verbose_name_plural': 'Felhasználói Pénztárcák',
            },
        ),
        migrations.DeleteModel(
            name='AlgorithmPricing',
        ),
        migrations.RemoveField(
            model_name='usercreditbalance',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='invoicerequest',
            options={'verbose_name': 'Számla Igénylés', 'verbose_name_plural': 'Számla Igénylések'},
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='invoicerequest',
            name='invoice_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Előfizetés (Hirdetésmentes)'), ('TOPUP', 'Egyenleg Feltöltés')], default='TOPUP', max_length=50, verbose_name='Számla típusa'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan', verbose_name='Előfizetési Csomag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoicerequest', verbose_name='Forrás számla igénylés'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.DeleteModel(
            name='UserCreditBalance',
        ),
    ]
