# Generated by Django 5.2.5 on 2026-01-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_serviceplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='plan_type',
            field=models.CharField(choices=[('AD_FREE', 'Hirdetésmentesség (Időalapú)'), ('ML_ACCESS', 'ML Funkciók (Időalapú)'), ('ANALYSIS', 'Elemzési Csomag (Darabszám alapú)')], max_length=20, verbose_name='Típus'),
        ),
    ]
