# Generated by Django 5.2.5 on 2025-11-13 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_financialtransaction_jobprice_userjobdiscount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='Vége'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kezdete'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_free_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.CreateModel(
            name='TopUpInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ft', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fizetendő Összeg (Ft)')),
                ('invoice_type', models.CharField(choices=[('CREDIT_TOPUP', 'Credit Feltöltés'), ('AD_FREE_SUBSCRIPTION', 'Hirdetésmentes Előfizetés')], default='CREDIT_TOPUP', max_length=30, verbose_name='Számla típusa')),
                ('billing_name', models.CharField(max_length=255, verbose_name='Számlázási Név')),
                ('billing_address', models.TextField(verbose_name='Számlázási Cím')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adószám')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Számlázási E-mail cím')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Igénylés dátuma')),
                ('status', models.CharField(choices=[('PENDING', 'Függőben'), ('SENT', 'Elküldve'), ('CANCELLED', 'Törölve')], default='PENDING', max_length=10, verbose_name='Státusz')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan', verbose_name='Előfizetési csomag')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_credit_target_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Jóváírás Személye')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_requested_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Igénylő felhasználó')),
            ],
            options={
                'verbose_name': 'Számlaigénylés (Feltöltés/Előfizetés)',
                'verbose_name_plural': 'Számlaigénylések (Feltöltés/Előfizetés)',
                'ordering': ['-request_date'],
            },
        ),
    ]
