# Generated by Django 5.2.5 on 2025-11-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_usersubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupinvoice',
            name='billing_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Számlázási E-mail cím'),
        ),
    ]
