# Generated by Django 5.2.5 on 2026-01-05 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_serviceplan_plan_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topupinvoice',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topupinvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_paid', to=settings.AUTH_USER_MODEL),
        ),
    ]
