# Generated by Django 5.2.5 on 2026-01-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_topupinvoice_target_user_alter_topupinvoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
    ]
