# Generated by Django 5.2.5 on 2025-11-17 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_financialtransaction_user'),
        ('diagnostics_jobs', '0020_diagnosticjob_billing_transaction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdViewStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Jelenlegi sorozat (napok)')),
                ('last_view_date', models.DateField(blank=True, null=True, verbose_name='Utolsó megtekintés dátuma')),
                ('total_rewards_earned', models.IntegerField(default=0, verbose_name='Összes szerzett jutalom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Darabszám változás')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Vásárlás'), ('USAGE', 'Felhasználás'), ('AD_REWARD', 'Hirdetésnézési jutalom')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics_jobs.diagnosticjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalysisBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_count', models.IntegerField(default=0, verbose_name='Elérhető elemzések száma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
