# Generated by Django 5.2.5 on 2026-01-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_usersubscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.serviceplan'),
        ),
    ]
