# Generated by Django 5.2.5 on 2025-11-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_adviewstreak_analysistransaction_useranalysisbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobprice',
            options={'ordering': ['price_ft'], 'verbose_name': 'Elemzési Csomag Ár', 'verbose_name_plural': 'Elemzési Csomag Árak'},
        ),
        migrations.RemoveField(
            model_name='jobprice',
            name='base_price_ft',
        ),
        migrations.RemoveField(
            model_name='jobprice',
            name='job_type',
        ),
        migrations.AddField(
            model_name='jobprice',
            name='analysis_count',
            field=models.IntegerField(default=1, verbose_name='Elemzések száma a csomagban'),
        ),
        migrations.AddField(
            model_name='jobprice',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Csomag neve'),
        ),
        migrations.AddField(
            model_name='jobprice',
            name='price_ft',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ár (Ft)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topupinvoice',
            name='related_analysis_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.jobprice', verbose_name='Kapcsolódó elemzési csomag'),
        ),
        migrations.AlterField(
            model_name='topupinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('CREDIT_TOPUP', 'Credit Feltöltés (Ft összeg)'), ('AD_FREE_SUBSCRIPTION', 'Hirdetésmentes Előfizetés'), ('ANALYSIS_PACKAGE', 'Elemzési Csomag')], default='ANALYSIS_PACKAGE', max_length=30, verbose_name='Számla típusa'),
        ),
    ]
