# Generated by Django 5.2.5 on 2025-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_jobprice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprice',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Csomag neve'),
            preserve_default=False,
        ),
    ]
