# Generated by Django 5.2.5 on 2025-11-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_jobprice_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviewstreak',
            options={'verbose_name': 'Hirdetésnézési Sorozat', 'verbose_name_plural': 'Hirdetésnézési Sorozatok'},
        ),
        migrations.AlterModelOptions(
            name='analysistransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Elemzési Tranzakció', 'verbose_name_plural': 'Elemzési Tranzakciók'},
        ),
        migrations.AlterModelOptions(
            name='useranalysisbalance',
            options={'verbose_name': 'Elemzési Egyenleg', 'verbose_name_plural': 'Elemzési Egyenlegek'},
        ),
        migrations.AlterField(
            model_name='adviewstreak',
            name='total_rewards_earned',
            field=models.IntegerField(default=0, verbose_name='Összes szerzett jutalom (db elemzés)'),
        ),
        migrations.AlterField(
            model_name='analysistransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Darabszám változás (+/-)'),
        ),
        migrations.AlterField(
            model_name='analysistransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
