# Generated by Django 5.2.5 on 2025-10-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(max_length=50, verbose_name='Sportág')),
                ('job_type', models.CharField(choices=[('GENERAL', 'Általános diagnosztika'), ('WRESTLING', 'Birkózás specifikus diagnosztika')], default='GENERAL', max_length=20)),
                ('video_url', models.URLField(verbose_name='Videó elérési út (Cloud Storage)')),
                ('status', models.CharField(choices=[('PENDING', 'Feldolgozásra vár'), ('PROCESSING', 'Feldolgozás alatt'), ('COMPLETED', 'Befejezve'), ('FAILED', 'Hiba történt')], default='PENDING', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Magasabb érték = előbbi feldolgozás')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, help_text='Diagnosztikai eredmények (JSON)', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosztikai feladat',
                'verbose_name_plural': 'Diagnosztikai feladatok',
                'ordering': ['-created_at'],
            },
        ),
    ]
