# Generated by Django 5.2.5 on 2025-10-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_data', '0005_alter_hrvandsleepdata_options_and_more'),
        ('diagnostics_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjob',
            name='hrv_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_jobs', to='biometric_data.hrvandsleepdata'),
        ),
        migrations.AddField(
            model_name='diagnosticjob',
            name='weight_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_jobs', to='biometric_data.weightdata'),
        ),
        migrations.AddField(
            model_name='diagnosticjob',
            name='workout_feedback_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_jobs', to='biometric_data.workoutfeedback'),
        ),
    ]
