# Generated by Django 5.2.5 on 2025-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0002_diagnosticjob_hrv_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjob',
            name='pdf_path',
            field=models.URLField(blank=True, null=True, verbose_name='Eredmény PDF URL'),
        ),
        migrations.AlterField(
            model_name='diagnosticjob',
            name='job_type',
            field=models.CharField(choices=[('GENERAL', 'Általános diagnosztika'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás specifikus diagnosztika')], default='GENERAL', max_length=50),
        ),
    ]
