# Generated by Django 5.2.5 on 2025-10-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0003_diagnosticjob_pdf_path_alter_diagnosticjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjob',
            name='job_type',
            field=models.CharField(choices=[('MOVEMENT_ASSESSMENT', 'Átfogó Mozgáselemzés (Régi - több szegmens egyben)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('POSTURE', 'Testtartás Értékelés'), ('ARM_MOBILITY', 'Váll/Kar Mobilitás Elemzés'), ('SQUAT', 'Guggolás Elemzés'), ('STANDING_JUMP', 'Ugrás Helyből Elemzés'), ('SINGLE_LEG_BALANCE', 'Egy lábon állás / Egyensúly'), ('PUSHUP', 'Fekvő Támasz / Törzsstabilitás')], default='POSTURE', max_length=50),
        ),
    ]
