# Generated by Django 5.2.5 on 2025-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0004_alter_diagnosticjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjob',
            name='job_type',
            field=models.CharField(choices=[('GENERAL', 'Általános (Régi)'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('SQUAT_ASSESSMENT', 'Guggolás Biomechanikai Elemzés'), ('POSTURE_ASSESSMENT', 'Testtartás Statikus/Dinamikus Elemzés')], default='MOVEMENT_ASSESSMENT', max_length=50),
        ),
    ]
