# Generated by Django 5.2.5 on 2025-10-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0005_alter_diagnosticjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjob',
            name='pdf_path',
            field=models.CharField(blank=True, help_text='A generált riport Cloud Storage URL-je', max_length=2048, null=True, verbose_name='Eredmény PDF URL'),
        ),
    ]
