# Generated by Django 5.2.5 on 2025-10-28 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0006_alter_diagnosticjob_pdf_path'),
        ('users', '0004_auto_20251017_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnthropometryProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
                ('height_cm', models.IntegerField(help_text='A felhasználó valós, hitelesített magassága centiméterben.', verbose_name='Testmagasság (cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Testsúly kilogrammban.', max_digits=5, null=True, verbose_name='Testsúly (kg)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trunk_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Törzshossz')),
                ('shoulder_width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Vállszélesség')),
                ('pelvis_width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Csípőszélesség')),
                ('left_upper_arm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal felkar hossza')),
                ('right_upper_arm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb felkar hossza')),
                ('left_forearm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal alkar hossza')),
                ('right_forearm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb alkar hossza')),
                ('left_thigh_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal comb hossza')),
                ('right_thigh_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb comb hossza')),
                ('left_shin_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal sípcsont hossza')),
                ('right_shin_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb sípcsont hossza')),
                ('reference_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics_jobs.diagnosticjob', verbose_name='Utolsó kalibrációs Job')),
            ],
            options={
                'verbose_name': 'Antropometriai profil',
                'verbose_name_plural': 'Antropometriai profilok',
            },
        ),
    ]
