# Generated by Django 5.2.5 on 2025-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0008_useranthropometryprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjob',
            name='job_type',
            field=models.CharField(choices=[('GENERAL', 'Általános (Régi)'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('SQUAT_ASSESSMENT', 'Guggolás Biomechanikai Elemzés'), ('POSTURE_ASSESSMENT', 'Testtartás Statikus/Dinamikus Elemzés'), ('ANTHROPOMETRY_ASSESSMENT', 'Antropometriai adatok becslése videó alapján')], default='MOVEMENT_ASSESSMENT', max_length=50),
        ),
    ]
