# Generated by Django 5.2.5 on 2025-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0009_alter_diagnosticjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjob',
            name='anthropometry_photo_url_front',
            field=models.URLField(blank=True, help_text='A statikus szemből készült fotó GCS elérési útja.', max_length=2048, null=True, verbose_name='Antropometria Kalibrációs Fotó URL (Szemből)'),
        ),
        migrations.AddField(
            model_name='diagnosticjob',
            name='anthropometry_photo_url_side',
            field=models.URLField(blank=True, help_text='A statikus oldalról készült fotó GCS elérési útja.', max_length=2048, null=True, verbose_name='Antropometria Kalibrációs Fotó URL (Oldalról)'),
        ),
        migrations.AddField(
            model_name='diagnosticjob',
            name='calibration_factor',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='A videók 3D-s koordinátáinak skálázásához használt arány (Valós Magasság / Becsült Magasság).', max_digits=10, null=True, verbose_name='MediaPipe Kalibrációs Faktor'),
        ),
        migrations.AddField(
            model_name='diagnosticjob',
            name='user_stated_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A kalibráció alapja, méterben (pl. 1.77).', max_digits=5, null=True, verbose_name='Felhasználó által megadott valós magasság (m)'),
        ),
        migrations.AlterField(
            model_name='diagnosticjob',
            name='job_type',
            field=models.CharField(choices=[('GENERAL', 'Általános (Régi)'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('SQUAT_ASSESSMENT', 'Guggolás Biomechanikai Elemzés'), ('POSTURE_ASSESSMENT', 'Testtartás Statikus/Dinamikus Elemzés'), ('ANTHROPOMETRY_CALIBRATION', 'Antropometria Kalibráció Két Képpel')], default='MOVEMENT_ASSESSMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnosticjob',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Videó elérési út (Cloud Storage)'),
        ),
    ]
