# Generated by Django 5.2.5 on 2025-10-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0010_diagnosticjob_anthropometry_photo_url_front_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranthropometryprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Antropometriai profil', 'verbose_name_plural': 'Antropometriai profilok'},
        ),
        migrations.AddField(
            model_name='useranthropometryprofile',
            name='calibration_factor',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Valós magasság / MediaPipe becsült magasság arány, a skálázáshoz.', max_digits=10, null=True, verbose_name='Kalibrációs faktor'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Születési dátum'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Testmagasság (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='left_forearm_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal alkar hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='left_shin_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal sípcsont hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='left_thigh_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal comb hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='left_upper_arm_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bal felkar hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='pelvis_width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Csípőszélesség (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='reference_job',
            field=models.ForeignKey(blank=True, help_text='Annak a diagnosztikai jobnak az azonosítója, amellyel ez a profil készült.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics_jobs.diagnosticjob', verbose_name='Utolsó kalibrációs feladat'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='right_forearm_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb alkar hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='right_shin_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb sípcsont hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='right_thigh_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb comb hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='right_upper_arm_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Jobb felkar hossza (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='shoulder_width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Vállszélesség (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='trunk_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Törzshossz (cm)'),
        ),
        migrations.AlterField(
            model_name='useranthropometryprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Testsúly (kg)'),
        ),
    ]
