# Generated by Django 5.2.5 on 2025-11-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0011_alter_useranthropometryprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjob',
            name='job_type',
            field=models.CharField(choices=[('GENERAL', 'Általános (Régi)'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('SQUAT_ASSESSMENT', 'Guggolás Biomechanikai Elemzés'), ('POSTURE_ASSESSMENT', 'Testtartás Statikus/Dinamikus Elemzés'), ('ANTHROPOMETRY_CALIBRATION', 'Antropometria Kalibráció Két Képpel'), ('SHOULDER_CIRCUMDUCTION', 'Vállkörzés elemzés')], default='MOVEMENT_ASSESSMENT', max_length=50),
        ),
    ]
