# Generated by Django 5.2.5 on 2025-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0012_alter_diagnosticjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Feldolgozásra vár'), ('QUEUED', 'Ütemezve'), ('PROCESSING', 'Feldolgozás alatt'), ('COMPLETED', 'Befejezve'), ('FAILED', 'Hiba történt')], default='PENDING', max_length=20),
        ),
    ]
