# Generated by Django 5.2.5 on 2025-11-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0014_alter_diagnosticjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranthropometryprofile',
            name='annotated_image_url',
            field=models.URLField(blank=True, help_text='A MediaPipe által generált kalibrált, feliratozott kép URL-je.', max_length=2048, null=True, verbose_name='Annotált antropometriai kép URL'),
        ),
    ]
