# Generated by Django 5.2.5 on 2025-11-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0015_useranthropometryprofile_annotated_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranthropometryprofile',
            name='manual_shin_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ha megadod, a rendszer ezt használja a MediaPipe becslés helyett.', max_digits=5, null=True, verbose_name='Lábszárhossz (kézi megadás, cm)'),
        ),
        migrations.AddField(
            model_name='useranthropometryprofile',
            name='manual_thigh_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ha megadod, a rendszer ezt használja a MediaPipe becslés helyett.', max_digits=5, null=True, verbose_name='Combhossz (kézi megadás, cm)'),
        ),
    ]
