# Generated by Django 5.2.5 on 2025-11-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0016_useranthropometryprofile_manual_shin_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjob',
            name='user_stated_shin_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Felhasználó által megadott lábszárhossz a kalibrációhoz (cm).', max_digits=5, null=True, verbose_name='Lábszárhossz (cm)'),
        ),
        migrations.AddField(
            model_name='diagnosticjob',
            name='user_stated_thigh_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Felhasználó által megadott combhossz a kalibrációhoz (cm).', max_digits=5, null=True, verbose_name='Combhossz (cm)'),
        ),
    ]
