# Generated by Django 5.2.5 on 2025-11-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0017_diagnosticjob_user_stated_shin_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjob',
            name='leg_calibration_factor',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='A comb és lábszár hossz alapján számolt korrekciós tényező.', max_digits=10, null=True, verbose_name='Láb-specifikus kalibrációs faktor'),
        ),
        migrations.AddField(
            model_name='useranthropometryprofile',
            name='leg_calibration_factor',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Combhossz + lábszárhossz alapján számított korrekciós tényező.', max_digits=10, null=True, verbose_name='Láb-specifikus kalibrációs faktor'),
        ),
    ]
