# Generated by Django 5.2.5 on 2025-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0018_diagnosticjob_leg_calibration_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjob',
            name='job_type',
            field=models.CharField(choices=[('GENERAL', 'Általános (Régi)'), ('MOVEMENT_ASSESSMENT', 'Általános mozgáselemzés (MediaPipe)'), ('WRESTLING', 'Birkózás Specifikus Elemzés'), ('SQUAT_ASSESSMENT', 'Guggolás Biomechanikai Elemzés'), ('POSTURE_ASSESSMENT', 'Testtartás Statikus/Dinamikus Elemzés'), ('ANTHROPOMETRY_CALIBRATION', 'Antropometria Kalibráció Két Képpel'), ('SHOULDER_CIRCUMDUCTION', 'Vállkörzés elemzés'), ('VERTICAL_JUMP', 'Helyből Magassági Ugrás Elemzés'), ('SINGLE_LEG_STANCE_LEFT', 'Egylábon Állás (Bal)'), ('SINGLE_LEG_STANCE_RIGHT', 'Egylábon Állás (Jobb)')], default='MOVEMENT_ASSESSMENT', max_length=50),
        ),
    ]
