# Generated by Django 5.2.5 on 2025-11-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_jobs', '0019_alter_diagnosticjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjob',
            name='billing_transaction_id',
            field=models.IntegerField(blank=True, help_text='A függőben lévő (PENDING) FinancialTransaction ID-je a foglaláshoz.', null=True, verbose_name='Kapcsolódó számlázási tranzakció ID'),
        ),
        migrations.AddField(
            model_name='diagnosticjob',
            name='calculated_cost_ft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A felhasználóra vonatkozó, kedvezményekkel számított futtatási költség.', max_digits=10, null=True, verbose_name='Kiszámított költség (Ft)'),
        ),
    ]
