steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/digit-train-web', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/digit-train-web']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - digit-train-web
  - --image
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/digit-train-web
  - --region
  - europe-west1
  - --platform
  - managed
  - --allow-unauthenticated
  env:
  - 'DJANGO_SETTINGS_MODULE=digiTTrain.production'