options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 20

steps:
# 0️⃣ Secret betöltése és .env.yaml generálás
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    secretEnv: ['DB_PASS', 'GEMINI_API_KEY']
    args:
      - -c
      - |
        echo "🔐 Generating .env.yaml with secrets..."
        
        echo "DB_NAME: digittraindb" > .env.yaml
        echo "DB_USER: root" >> .env.yaml
        echo "DB_PASS: $$DB_PASS" >> .env.yaml 
        echo "DJANGO_SETTINGS_MODULE: digiTTrain.settings" >> .env.yaml
        echo "ALLOWED_HOSTS: digit-train-web-195803356854.europe-west1.run.app,digit-train.hu,www.digit-train.hu" >> .env.yaml
        echo "CLOUDSQL_CONNECTION_NAME: digittrain-projekt:europe-west1:digitrain-mysql-db-west1" >> .env.yaml
        echo "GS_BUCKET_NAME: digittrain-media-publikus-miska1984" >> .env.yaml
        echo "GS_PROJECT_ID: digittrain-projekt" >> .env.yaml
        echo "GS_LOCATION: europe-west1" >> .env.yaml
        echo "ENVIRONMENT: production" >> .env.yaml
        echo "GCP_SA_KEY_PATH: /app/gcp_service_account.json" >> .env.yaml
        echo "REDIS_HOST: 10.32.84.131" >> .env.yaml
        echo "REDIS_PORT: \"6379\"" >> .env.yaml
        echo "TF_CPP_MIN_LOG_LEVEL: \"2\"" >> .env.yaml
        echo "CUDA_VISIBLE_DEVICES: \"-1\"" >> .env.yaml
        echo "GEMINI_API_KEY: \"$$GEMINI_API_KEY\"" >> .env.yaml
        echo "USE_GCS_STATIC: \"true\"" >> .env.yaml
        echo "BUILD_MODE: \"false\"" >> .env.yaml
        echo "MPLCONFIGDIR: /tmp/matplotlib_cache" >> .env.yaml
        
        echo "✅ .env.yaml generálva."

# 1️⃣ GCP kulcs letöltés
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - >
        gsutil cp gs://digittrain-secrets/gcp_service_account.json ./gcp_service_account.json

# 2️⃣ Build App image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest', '.']

# 3️⃣ Push App image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest']

# 4️⃣ Django migráció
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs execute migrate-job --region=europe-west1 --wait || \
        gcloud run jobs create migrate-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","migrate","--verbosity","3" \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1
        
# 5️⃣ Django Collectstatic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs execute collectstatic-job --region=europe-west1 --wait || \
        gcloud run jobs create collectstatic-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","collectstatic","--noinput" \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1

# 6️⃣ Deploy Web service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - digit-train-web
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --env-vars-file
      - .env.yaml
      - --add-cloudsql-instances
      - digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector
      - redis-connector
      - --vpc-egress
      - private-ranges-only
      - --min-instances
      - '0'
      - --max-instances
      - '10'
      - --memory
      - 2Gi
      - --cpu
      - '2'
      - --timeout
      - 300s

# 7️⃣ Celery Worker Job frissítése (Videóelemzéshez kell!)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update 
      - celery-worker-job
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
      - --region
      - europe-west1
      - --command=celery
      - --args=-A,digiTTrain,worker,-l,info
      - --env-vars-file=.env.yaml
      - --set-cloudsql-instances=digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector=redis-connector
      - --task-timeout=3600s
      - --max-retries=3
      - --cpu=4
      - --memory=8Gi
      - --quiet

# 8️⃣ Daily ML Job frissítése (AI elemzéshez kell!)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - daily-ml-job
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
      - --region
      - europe-west1
      - --command
      - python
      - --args
      - manage.py,run_daily_ml
      - --env-vars-file
      - .env.yaml
      - --set-cloudsql-instances
      - digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector
      - redis-connector
      - --task-timeout
      - 7200s
      - --cpu
      - '4'
      - --memory
      - 8Gi
      - --quiet

# 9️⃣ Cloud Scheduler beállítása (A MÁR TESZTELT, JÓ URL-lel)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud scheduler jobs create http daily-ml-trigger \
          --schedule="0 2 * * *" \
          --location=europe-west1 \
          --uri="https://run.googleapis.com/v2/projects/digittrain-projekt/locations/europe-west1/jobs/daily-ml-job:run" \
          --http-method=POST \
          --oauth-service-account-email=195803356854-compute@developer.gserviceaccount.com || \
        gcloud scheduler jobs update http daily-ml-trigger \
          --schedule="0 2 * * *" \
          --location=europe-west1 \
          --uri="https://run.googleapis.com/v2/projects/digittrain-projekt/locations/europe-west1/jobs/daily-ml-job:run" \
          --http-method=POST \
          --oauth-service-account-email=195803356854-compute@developer.gserviceaccount.com

timeout: 3600s

availableSecrets:
  secretManager:
    - versionName: projects/digittrain-projekt/secrets/db_password/versions/latest
      env: 'DB_PASS'
    - versionName: projects/digittrain-projekt/secrets/gemini_api_key/versions/latest
      env: 'GEMINI_API_KEY'