steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest']
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - jobs
  - execute
  - migrate-job
  - --region=europe-west1
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - jobs
  - execute
  - migrate-job
  - --region=europe-west1
  # Add environment variables for the migrate job
  - --set-env-vars
  - "DB_HOST=<YOUR_DB_IP_ADDRESS>"
  - "DB_USER=<YOUR_DB_USER>"
  - "DB_PASS=<YOUR_DB_PASSWORD>"
  - "DB_NAME=<YOUR_DB_NAME>"
  - "DJANGO_SETTINGS_MODULE=digiTTrain.settings"

options:
  logging: CLOUD_LOGGING_ONLY