steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - jobs
  - execute
  - migrate-job
  - --region=europe-west1

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - digit-train-web
  - --image
  - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
  - --region
  - europe-west1
  - --platform
  - managed
  - --allow-unauthenticated