options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 20


steps:
# 0️⃣ Secret betöltése és .env.yaml generálás
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    secretEnv: ['DB_PASS']
    args:
      - -c
      - |
        echo "🔐 Generating .env.yaml with secrets..."
        
        echo "DB_NAME: digittraindb" > .env.yaml
        echo "DB_USER: root" >> .env.yaml
        echo "DB_PASS: $$DB_PASS" >> .env.yaml 
        echo "DJANGO_SETTINGS_MODULE: digiTTrain.settings" >> .env.yaml
        echo "ALLOWED_HOSTS: digit-train-web-195803356854.europe-west1.run.app,digit-train.hu,www.digit-train.hu" >> .env.yaml
        echo "CLOUDSQL_CONNECTION_NAME: digittrain-projekt:europe-west1:digitrain-mysql-db-west1" >> .env.yaml
        echo "GS_BUCKET_NAME: digittrain-media-publikus-miska1984" >> .env.yaml
        echo "GS_PROJECT_ID: digittrain-projekt" >> .env.yaml
        echo "GS_LOCATION: europe-west1" >> .env.yaml
        echo "ENVIRONMENT: production" >> .env.yaml
        echo "GCP_SA_KEY_PATH: /app/gcp_service_account.json" >> .env.yaml
        echo "REDIS_HOST: 10.32.84.131" >> .env.yaml
        echo "REDIS_PORT: \"6379\"" >> .env.yaml
        echo "CLOUD_RUN_JOB_NAME: celery-worker-job" >> .env.yaml
        echo "TF_CPP_MIN_LOG_LEVEL: \"2\"" >> .env.yaml
        echo "CUDA_VISIBLE_DEVICES: \"-1\"" >> .env.yaml
        echo "USE_GCS_STATIC: \"true\"" >> .env.yaml
        echo "BUILD_MODE: \"false\"" >> .env.yaml
        echo "MPLCONFIGDIR: /tmp/matplotlib_cache" >> .env.yaml
        
        echo "✅ .env.yaml tartalom:"
        cat .env.yaml

# 1️⃣ GCP kulcs letöltés
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - >
        gsutil cp gs://digittrain-secrets/gcp_service_account.json ./gcp_service_account.json

# 2️⃣ Build Web image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest', '.']

# 3️⃣ Push Web image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest']

# 4️⃣ Build Worker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.worker', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest', '.']

# 5️⃣ Push Worker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest']

# 6️⃣ Django migráció
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs execute migrate-job --region=europe-west1 --wait || \
        gcloud run jobs create migrate-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","migrate","--verbosity","3" \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1
        
# 6.1 5️⃣ Django Collectstatic (Feltöltés a GCS-be)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs execute collectstatic-job --region=europe-west1 --wait || \
        gcloud run jobs create collectstatic-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","collectstatic","--noinput" \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1

# 7️⃣ Deploy Web service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - digit-train-web
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --env-vars-file
      - .env.yaml
      - --add-cloudsql-instances
      - digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector
      - redis-connector
      - --vpc-egress
      - private-ranges-only
      - --min-instances
      - '0'
      - --max-instances
      - '10'
      - --memory
      - 2Gi
      - --cpu
      - '2'
      - --timeout
      - 300s

# 8️⃣ Deploy Celery Worker Job (LÉTREHOZÁS az első futáshoz)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update 
      - celery-worker-job
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest
      - --region
      - europe-west1
      - --command=celery
      - --args=-A,digiTTrain,worker,-l,info
      - --env-vars-file=.env.yaml
      - --set-cloudsql-instances=digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector=redis-connector
      - --task-timeout=3600s
      - --max-retries=3
      - --cpu=4
      - --memory=8Gi
      - --quiet
      
# 9️⃣ Deploy Celery ML Worker Job (LÉTREHOZÁS az első futáshoz)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update # Visszaállítjuk create-re
      - celery-ml-worker-job
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest
      - --region
      - europe-west1
      - --command=celery
      - --args=-A,digiTTrain,worker,-l,info,-Q,ml_engine
      - --env-vars-file=.env.yaml
      - --set-cloudsql-instances=digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector=redis-connector
      - --task-timeout=3600s
      - --max-retries=3
      - --cpu=4
      - --memory=8Gi
      - --quiet
      
# 🆕 10️⃣ Deploy / Recreate Daily ML Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔁 Recreating daily-ml-job..."
        gcloud run jobs delete daily-ml-job --region=europe-west1 --quiet || true

        gcloud run jobs create daily-ml-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command python \
          --args manage.py,run_daily_ml \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1 \
          --vpc-connector redis-connector \
          --task-timeout 7200s \
          --max-retries 2 \
          --cpu 4 \
          --memory 8Gi \
          --quiet

# 11️⃣ Cloud Scheduler beállítása (JAVÍTOTT URL)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud scheduler jobs create http daily-ml-trigger \
          --schedule="0 2 * * *" \
          --location=europe-west1 \
          --uri="https://run.googleapis.com/v2/projects/digittrain-projekt/locations/europe-west1/jobs/daily-ml-job:runExecution" \
          --http-method=POST \
          --oauth-service-account-email=195803356854-compute@developer.gserviceaccount.com || \
        gcloud scheduler jobs update http daily-ml-trigger \
          --schedule="0 2 * * *" \
          --location=europe-west1 \
          --uri="https://run.googleapis.com/v2/projects/digittrain-projekt/locations/europe-west1/jobs/daily-ml-job:runExecution" \
          --http-method=POST \
          --oauth-service-account-email=195803356854-compute@developer.gserviceaccount.com

timeout: 3600s

# 🔑 GLOBÁLIS SECRETS KONFIGURÁCIÓ
availableSecrets:
  secretManager:
    - versionName: projects/digittrain-projekt/secrets/db_password/versions/latest
      env: 'DB_PASS'