steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest']

  # Create or update migrate-job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs update migrate-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","migrate","--verbosity","3" \
          --set-env-vars=DB_NAME=digittraindb,DB_USER=root,DB_PASS=MIshek001-1984,DJANGO_SETTINGS_MODULE=digiTTrain.settings,ALLOWED_HOSTS=digit-train-web-195803356854.europe-west1.run.app,CLOUDSQL_CONNECTION_NAME=digittrain-projekt:europe-west1:digitrain-mysql-db-west1,ENVIRONMENT=production \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1 \
        || gcloud run jobs create migrate-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","migrate","--verbosity","3" \
          --set-env-vars=DB_NAME=digittraindb,DB_USER=root,DB_PASS=MIshek001-1984,DJANGO_SETTINGS_MODULE=digiTTrain.settings,ALLOWED_HOSTS=digit-train-web-195803356854.europe-west1.run.app,CLOUDSQL_CONNECTION_NAME=digittrain-projekt:europe-west1:digitrain-mysql-db-west1,ENVIRONMENT=production \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1

  # Execute migrate-job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - migrate-job
      - --region=europe-west1
  
# Create or update initial-data-job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs update initial-data-job \
        --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
        --region europe-west1 \
        --command "python" \
        --args "manage.py","populate_initial_data" \
        --set-env-vars=DB_NAME=digittraindb,DB_USER=root,DB_PASS=MIshek001-1984,DJANGO_SETTINGS_MODULE=digiTTrain.settings,ALLOWED_HOSTS=digit-train-web-195803356854.europe-west1.run.app,CLOUDSQL_CONNECTION_NAME=digittrain-projekt:europe-west1:digitrain-mysql-db-west1,ENVIRONMENT=production \
        --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1 \
      || gcloud run jobs create initial-data-job \
        --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
        --region europe-west1 \
        --command "python" \
        --args "manage.py","populate_initial_data" \
        --set-env-vars=DB_NAME=digittraindb,DB_USER=root,DB_PASS=MIshek001-1984,DJANGO_SETTINGS_MODULE=digiTTrain.settings,ALLOWED_HOSTS=digit-train-web-195803356854.europe-west1.run.app,CLOUDSQL_CONNECTION_NAME=digittrain-projekt:europe-west1:digitrain-mysql-db-west1,ENVIRONMENT=production \
        --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1

# Execute initial-data-job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: # FIX: A korábbi verzióban a `run` és a `jobs` is hibásan volt behúzva
      - run
      - jobs
      - execute
      - initial-data-job
      - --region=europe-west1

  # Deploy Cloud Run service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - digit-train-web
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars=DB_NAME=digittraindb,DB_USER=root,DB_PASS=MIshek001-1984,DJANGO_SETTINGS_MODULE=digiTTrain.settings,ALLOWED_HOSTS=digit-train-web-195803356854.europe-west1.run.app,CLOUDSQL_CONNECTION_NAME=digittrain-projekt:europe-west1:digitrain-mysql-db-west1,GS_BUCKET_NAME=digittrain-media-publikus-miska1984,GS_PROJECT_ID=digittrain-projekt,GS_LOCATION=europe-west1,ENVIRONMENT=production
      - --add-cloudsql-instances
      - digittrain-projekt:europe-west1:digitrain-mysql-db-west1

options:
  logging: CLOUD_LOGGING_ONLY