options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 20
  substitution_option: ALLOW_LOOSE

steps:
# 0️⃣ Secret betöltése és .env.yaml generálás
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    secretEnv: ['DB_PASS']
    args:
      - -c
      - |
        echo "🔐 Generating .env.yaml with secrets..."
        
        cat > .env.yaml <<ENVEOF
        DB_NAME: digittraindb
        DB_USER: root
        DB_PASS: ${DB_PASS}
        DJANGO_SETTINGS_MODULE: digiTTrain.settings
        ENVIRONMENT: production
        BUILD_MODE: "false"
        
        CLOUDSQL_CONNECTION_NAME: digittrain-projekt:europe-west1:digitrain-mysql-db-west1
        GS_BUCKET_NAME: digittrain-media-publikus-miska1984
        GS_PROJECT_ID: digittrain-projekt
        GS_LOCATION: europe-west1
        GCP_SA_KEY_PATH: /app/gcp_service_account.json
        
        ALLOWED_HOSTS: digit-train-web-195803356854.europe-west1.run.app,digit-train.hu,www.digit-train.hu
        USE_GCS_STATIC: "false"
        
        REDIS_HOST: 10.32.84.131
        REDIS_PORT: "6379"
        
        CLOUD_RUN_JOB_NAME: celery-worker-job
        
        TF_CPP_MIN_LOG_LEVEL: "2"
        CUDA_VISIBLE_DEVICES: "-1"
        ENVEOF

  # 1️⃣ GCP kulcs letöltés (Változatlan)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - >
        gsutil cp gs://digittrain-secrets/gcp_service_account.json ./gcp_service_account.json

  # 2️⃣ Build Web image (Változatlan)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest', '.']

  # 3️⃣ Push Web image (Változatlan)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest']

  # 4️⃣ Build Worker image (Változatlan)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.worker', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest', '.']

  # 5️⃣ Push Worker image (Változatlan)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest']

  # 6️⃣ Django migráció (Változatlan)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs execute migrate-job --region=europe-west1 --wait || \
        gcloud run jobs create migrate-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","migrate","--verbosity","3" \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1

  # 7️⃣ Deploy Web service (Változatlan)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - digit-train-web
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --env-vars-file
      - .env.yaml
      - --add-cloudsql-instances
      - digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector
      - redis-connector
      - --vpc-egress
      - private-ranges-only
      - --min-instances
      - '0'
      - --max-instances
      - '10'
      - --memory
      - 2Gi
      - --cpu
      - '2'
      - --timeout
      - 300s

  # 8️⃣ Deploy Celery Worker Job (Változatlan)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - celery-worker-job
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest
      - --region
      - europe-west1
      - --command=celery
      - --args=-A,digiTTrain,worker,-l,info
      - --env-vars-file=.env.yaml
      - --add-cloudsql-instances=digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector=redis-connector
      - --task-timeout=3600s
      - --max-retries=3
      - --cpu=4
      - --memory=8Gi
      
    # 9️⃣ Deploy Celery ML Worker Job (Változatlan)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - celery-ml-worker-job
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/worker:latest
      - --region
      - europe-west1
      - --command=celery
      - --args=-A,digiTTrain,worker,-l,info,-Q,ml_engine
      - --env-vars-file=.env.yaml
      - --add-cloudsql-instances=digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector=redis-connector
      - --task-timeout=3600s
      - --max-retries=3
      - --cpu=4
      - --memory=8Gi

timeout: 3600s

# 🔑 Secrets konfiguráció (EZ A RÉSZ KELL A FÁJL VÉGÉRE!)
availableSecrets:
  secretManager:
  - versionName: projects/digittrain-projekt/secrets/db_password/versions/latest
    env: 'DB_PASS'