# Cloud Build beállítások
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 20
  substitution_option: ALLOW_LOOSE

steps:
  # 0️⃣ Létrehozzuk az .env.yaml fájlt a környezeti változókkal + CORS konfiguráció
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        # Hardcoded .env.yaml generálás
        cat > .env.yaml <<'ENVEOF'
        DB_NAME: digittraindb
        DB_USER: root
        DB_PASS: MIshek001-1984
        DJANGO_SETTINGS_MODULE: digiTTrain.settings
        ALLOWED_HOSTS: digit-train-web-195803356854.europe-west1.run.app,digit-train.hu,www.digit-train.hu
        CLOUDSQL_CONNECTION_NAME: digittrain-projekt:europe-west1:digitrain-mysql-db-west1
        GS_BUCKET_NAME: digittrain-media-publikus-miska1984
        GS_PROJECT_ID: digittrain-projekt
        GS_LOCATION: europe-west1
        ENVIRONMENT: production
        GCP_SA_KEY_PATH: /app/gcp_service_account.json
        REDIS_HOST: 10.32.84.131
        REDIS_PORT: "6379"
        ENVEOF
        
        echo "✅ .env.yaml létrehozva:"
        cat .env.yaml
        
        # CORS konfiguráció
        echo "🌐 CORS konfiguráció alkalmazása..."
        gsutil cors set cors-config.json gs://digittrain-media-publikus-miska1984
        gsutil cors get gs://digittrain-media-publikus-miska1984

  # 1️⃣ Letöltjük a GCP kulcsot a Cloud Storage-ből
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - >
        echo "🔑 GCP service account kulcs letöltése...";
        gsutil cp gs://digittrain-secrets/gcp_service_account.json ./gcp_service_account.json;
        ls -l ./gcp_service_account.json

  # 2️⃣ Docker image build - Web Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest', '.']

  # 3️⃣ Docker image push - Web Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest']

  # 4️⃣ Docker image build - Celery Worker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.worker', '-t', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/celery-worker:latest', '.']

  # 5️⃣ Docker image push - Celery Worker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/celery-worker:latest']

  # 6️⃣ Migráció futtatása
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs update migrate-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","migrate","--verbosity","3" \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1 \
        || gcloud run jobs create migrate-job \
          --image europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest \
          --region europe-west1 \
          --command "python" \
          --args "manage.py","migrate","--verbosity","3" \
          --env-vars-file .env.yaml \
          --set-cloudsql-instances digittrain-projekt:europe-west1:digitrain-mysql-db-west1
        
        echo "🔄 Migráció futtatása..."
        gcloud run jobs execute migrate-job --region=europe-west1 --wait

  # 7️⃣ Initial data job futtatása
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "📦 Initial data job futtatása..."
        gcloud run jobs execute initial-data-job --region=europe-west1 --wait || echo "⚠️ Initial data job már futott vagy nem létezik"

  # 8️⃣ Deploy Web Service (VPC Connector-ral)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - digit-train-web
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/app:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --env-vars-file
      - .env.yaml
      - --add-cloudsql-instances
      - digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector
      - redis-connector
      - --vpc-egress
      - private-ranges-only
      - --min-instances
      - '0'
      - --max-instances
      - '10'
      - --memory
      - 2Gi
      - --cpu
      - '2'
      - --timeout
      - 300s

  # 9️⃣ Deploy Celery Worker Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - digittrain-celery-worker
      - --image
      - europe-west1-docker.pkg.dev/digittrain-projekt/digittrain-web/celery-worker:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --no-allow-unauthenticated
      - --env-vars-file
      - .env.yaml
      - --add-cloudsql-instances
      - digittrain-projekt:europe-west1:digitrain-mysql-db-west1
      - --vpc-connector
      - redis-connector
      - --vpc-egress
      - private-ranges-only
      - --min-instances
      - '1'
      - --max-instances
      - '3'
      - --memory
      - 2Gi
      - --cpu
      - '2'
      - --no-cpu-throttling

timeout: 3600s

options:
  logging: CLOUD_LOGGING_ONLY