# Generated by Django 5.2.5 on 2025-09-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_role_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Keresztnév')),
                ('last_name', models.CharField(max_length=100, verbose_name='Vezetéknév')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Születési dátum')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.club', verbose_name='Egyesület')),
                ('registered_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placeholder_record', to=settings.AUTH_USER_MODEL, verbose_name='Regisztrált Felhasználó')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sport', verbose_name='Sportág')),
            ],
            options={
                'verbose_name': 'Ideiglenes Sportoló',
                'verbose_name_plural': 'Ideiglenes Sportolók',
            },
        ),
        migrations.CreateModel(
            name='PhysicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(verbose_name='Dátum')),
                ('assessment_type', models.CharField(choices=[('GRIP_STRENGTH', 'Markoerő (kg)'), ('PULL_UPS', 'Húzódzkodás (ismétlés)'), ('YO_YO', 'Ingafutás (szint)'), ('JUMP_HEIGHT', 'Ugrás Magasság (cm)'), ('WEIGHT', 'Testsúly (kg)')], max_length=50, verbose_name='Felmérés Típusa')),
                ('result_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Eredmény')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('athlete_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Regisztrált Sportoló')),
                ('coach', models.ForeignKey(limit_choices_to={'role__name': 'Edző'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felmérést végző Edző')),
                ('athlete_placeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_assessments', to='assessment.placeholderathlete', verbose_name='Ideiglenes Sportoló')),
            ],
            options={
                'verbose_name': 'Edzői Felmérés',
                'verbose_name_plural': 'Edzői Felmérések',
            },
        ),
    ]
