# Generated by Django 5.2.5 on 2025-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholderathlete',
            name='gender',
            field=models.CharField(choices=[('M', 'Fiú'), ('F', 'Lány')], default='M', max_length=1, verbose_name='Nem'),
        ),
    ]
