# Generated by Django 5.2.5 on 2026-01-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpredictionresult',
            name='coach_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
