# Generated by Django 5.2.5 on 2026-01-12 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0003_dittamissedquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dittamissedquery',
            options={'verbose_name': 'Ditta Hiányzó Ismeret', 'verbose_name_plural': 'Ditta Hiányzó Ismeretek'},
        ),
        migrations.AddField(
            model_name='dittamissedquery',
            name='context_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dittamissedquery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
