# Generated by Django 5.2.5 on 2025-09-06 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Reggeli súly (kg)')),
                ('pre_workout_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Edzés előtti súly (kg)')),
                ('post_workout_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Edzés utáni súly (kg)')),
                ('fluid_intake', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Edzés közbeni folyadékfogyasztás (l)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Testzsír (%)')),
                ('muscle_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Izom (%)')),
                ('bone_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Csonttömeg (kg)')),
                ('workout_date', models.DateField(auto_now_add=True, verbose_name='Edzés napja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Súlykontroll adat',
                'verbose_name_plural': 'Súlykontroll adatok',
                'ordering': ['-workout_date', '-created_at'],
            },
        ),
    ]
