# Generated by Django 5.2.5 on 2025-09-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightdata',
            name='workout_date',
            field=models.DateField(verbose_name='Edzés napja'),
        ),
    ]
