# Generated by Django 5.2.5 on 2025-09-24 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_data', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRVandSleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='HRV (ms)')),
                ('sleep_quality', models.IntegerField(blank=True, help_text='1-10 közötti skálán', null=True, verbose_name='Alvásminőség')),
                ('recorded_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HRV és alvás adat',
                'verbose_name_plural': 'HRV és alvás adatok',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RunningPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_distance_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Táv (km)')),
                ('run_duration', models.DurationField(verbose_name='Idő')),
                ('run_min_hr', models.IntegerField(blank=True, null=True, verbose_name='Minimum pulzus (bpm)')),
                ('run_max_hr', models.IntegerField(blank=True, null=True, verbose_name='Maximum pulzus (bpm)')),
                ('run_avg_hr', models.IntegerField(blank=True, null=True, verbose_name='Átlagos pulzus (bpm)')),
                ('run_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Futó teljesítmény',
                'verbose_name_plural': 'Futó teljesítmények',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_grip_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Jobb marokerő (kg)')),
                ('left_grip_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bal marokerő (kg)')),
                ('workout_intensity', models.IntegerField(blank=True, help_text='1-10 közötti skálán', null=True, verbose_name='Edzésintenzitás')),
                ('workout_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edzésvisszajelzés',
                'verbose_name_plural': 'Edzésvisszajelzések',
                'ordering': ['-workout_date'],
            },
        ),
    ]
