# Generated by Django 5.2.5 on 2025-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_data', '0002_alter_weightdata_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightdata',
            name='workout_date',
            field=models.DateField(auto_now_add=True, verbose_name='Edzés napja'),
        ),
    ]
