# Generated by Django 5.2.5 on 2025-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_data', '0003_hrvandsleepdata_runningperformance_workoutfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrvandsleepdata',
            options={},
        ),
        migrations.AddField(
            model_name='hrvandsleepdata',
            name='alertness',
            field=models.IntegerField(blank=True, help_text='1-10 közötti skálán', null=True, verbose_name='Éberség / Közérzet'),
        ),
    ]
