# Generated by Django 5.2.5 on 2025-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_data', '0004_alter_hrvandsleepdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrvandsleepdata',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'HRV és Alvás Adat', 'verbose_name_plural': 'HRV és Alvás Adatok'},
        ),
        migrations.AlterField(
            model_name='hrvandsleepdata',
            name='alertness',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Extrém fáradtság, kimerültség'), (2, '2 - Nagyon fáradt, nehéz koncentrálni'), (3, '3 - Fáradt, de működőképes'), (4, '4 - Átlagos, pici kávé kell'), (5, '5 - Éber, fókuszált'), (6, '6 - Nagyon éber, energikus'), (7, '7 - Magas energia szint'), (8, '8 - Kiegyensúlyozottan motivált'), (9, '9 - Mentálisan a csúcson'), (10, '10 - Tökéletes közérzet')], null=True, verbose_name='Éberség / Közérzet'),
        ),
        migrations.AlterField(
            model_name='hrvandsleepdata',
            name='sleep_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Nagyon rossz minőségű'), (2, '2 - Rossz, gyakori ébredéssel'), (3, '3 - Átlag alatti, nem pihentető'), (4, '4 - Átlagos, kielégítő'), (5, '5 - Jó, gyors elalvással'), (6, '6 - Nagyon jó, mély alvással'), (7, '7 - Kipihent, regeneráló'), (8, '8 - Kiváló, ébredés nélkül'), (9, '9 - Szinte tökéletes'), (10, '10 - Tökéletes alvás')], null=True, verbose_name='Alvás Minősége'),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='workout_intensity',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Nagyon könnyű (Bemelegítés, regeneráló)'), (2, '2 - Könnyű (Szinte nincs terhelés)'), (3, '3 - Közepes (Kényelmes, hosszan tartható)'), (4, '4 - Kicsit kemény (Megéri az erőlködés)'), (5, '5 - Mérsékelt (Kellemesen nehéz)'), (6, '6 - Elég kemény (Kicsit nehezebb, mint a komfortzóna)'), (7, '7 - Kemény (Komfortzónán kívül, még kontrollálható)'), (8, '8 - Nagyon kemény (Nehéz fenntartani)'), (9, '9 - Extrém (Csak rövidebb ideig tartható)'), (10, '10 - Maximális (Minden erőfeszítés)')], help_text='1-10 közötti skálán', null=True, verbose_name='Edzésintenzitás'),
        ),
    ]
