# Generated by Django 5.2.5 on 2026-02-20 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_data', '0005_alter_hrvandsleepdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrvandsleepdata',
            name='recorded_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Rögzítés napja'),
        ),
        migrations.AlterField(
            model_name='runningperformance',
            name='run_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Futás napja'),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='workout_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Edzés napja'),
        ),
    ]
