# Generated by Django 5.2.5 on 2025-10-09 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(help_text='pl. wrestling, running, swimming', max_length=50, verbose_name='Sportág')),
                ('source_type', models.CharField(choices=[('video', 'Videó elemzés'), ('biometric', 'Biometrikus elemzés'), ('combined', 'Kombinált')], default='combined', max_length=30, verbose_name='Forrástípus')),
                ('video_file_url', models.URLField(blank=True, null=True, verbose_name='Videó fájl URL-je (Cloud Storage)')),
                ('status', models.CharField(choices=[('pending', 'Folyamatban'), ('processing', 'Feldolgozás alatt'), ('done', 'Kész'), ('error', 'Hiba')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Sportoló')),
            ],
            options={
                'verbose_name': 'Diagnosztikai futás',
                'verbose_name_plural': 'Diagnosztikai futások',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WrestlingSpecificMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_execution_score', models.FloatField(blank=True, null=True, verbose_name='Technikai pontosság (%)')),
                ('balance_stability', models.FloatField(blank=True, null=True, verbose_name='Egyensúly stabilitás (%)')),
                ('explosiveness_index', models.FloatField(blank=True, null=True, verbose_name='Robbanékonysági index')),
                ('joint_symmetry_score', models.FloatField(blank=True, null=True, verbose_name='Ízületi szimmetria (%)')),
                ('core_engagement_level', models.FloatField(blank=True, null=True, verbose_name='Törzs aktivitás (%)')),
                ('endurance_estimate', models.FloatField(blank=True, null=True, verbose_name='Állóképesség becslés (%)')),
                ('injury_risk_score', models.FloatField(blank=True, null=True, verbose_name='Sérüléskockázati index')),
                ('movement_efficiency', models.FloatField(blank=True, null=True, verbose_name='Mozgáshatékonyság (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wrestling_metrics', to='diagnostics.diagnosticsession', verbose_name='Kapcsolódó diagnosztikai futás')),
            ],
            options={
                'verbose_name': 'Birkózó diagnosztikai metrika',
                'verbose_name_plural': 'Birkózó diagnosztikai metrikák',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='pl. general, wrestling', max_length=50, verbose_name='Metrika kategória')),
                ('name', models.CharField(help_text='pl. HydrationEfficiency vagy TechniqueExecutionScore', max_length=100, verbose_name='Metrika neve')),
                ('value', models.FloatField(verbose_name='Érték')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mértékegység')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Pontszám (0-100 skálán)')),
                ('interpretation', models.TextField(blank=True, null=True, verbose_name='Szöveges értelmezés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='diagnostics.diagnosticsession', verbose_name='Kapcsolódó diagnosztikai futás')),
            ],
            options={
                'verbose_name': 'Diagnosztikai metrika',
                'verbose_name_plural': 'Diagnosztikai metrikák',
                'indexes': [models.Index(fields=['category', 'name'], name='diagnostics_categor_a60108_idx')],
            },
        ),
    ]
