"""empty message

Revision ID: 0ecf2e84e7d7
Revises: 99e5997b31e1
Create Date: 2025-02-19 09:40:25.241861

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0ecf2e84e7d7"
down_revision = "99e5997b31e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes_parents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("athlete_parents")
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["user_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.create_table(
        "athlete_parents",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "athlete_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "parent_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"], ["athletes.id"], name="athlete_parents_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["parents.id"], name="athlete_parents_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("athletes_parents")
    # ### end Alembic commands ###
