"""empty message

Revision ID: 88ef27cc569e
Revises:
Create Date: 2025-02-18 10:29:08.577510

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "88ef27cc569e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "clubs_sports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "coaches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("club_sport_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_sport_id"],
            ["clubs_sports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "athletes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("club_sport_id", sa.Integer(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_sport_id"],
            ["clubs_sports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "athlete_parents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leaders", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )
        batch_op.alter_column(
            "club_id", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leaders", schema=None) as batch_op:
        batch_op.alter_column(
            "club_id", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )
        batch_op.alter_column(
            "user_id", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )

    op.drop_table("athlete_parents")
    op.drop_table("athletes")
    op.drop_table("coaches")
    op.drop_table("clubs_sports")
    op.drop_table("parents")
    # ### end Alembic commands ###
