"""empty message

Revision ID: 99e5997b31e1
Revises: 88ef27cc569e
Create Date: 2025-02-18 15:01:40.740813

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99e5997b31e1"
down_revision = "88ef27cc569e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("coach_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "coaches", ["coach_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parents", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("coach_id")

    # ### end Alembic commands ###
