"""empty message

Revision ID: da19eafe3aac
Revises: 0ecf2e84e7d7
Create Date: 2025-02-19 10:08:45.482905

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "da19eafe3aac"
down_revision = "0ecf2e84e7d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_constraint("athletes_ibfk_1", type_="foreignkey")
        batch_op.drop_column("club_sport_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "club_sport_id",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.create_foreign_key(
            "athletes_ibfk_1", "clubs_sports", ["club_sport_id"], ["id"]
        )

    # ### end Alembic commands ###
