# Generated by Django 5.2.5 on 2025-09-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Dátum')),
                ('start_time', models.TimeField(verbose_name='Kezdés ideje')),
                ('duration_minutes', models.IntegerField(verbose_name='Időtartam (perc)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Helyszín')),
                ('coach', models.ForeignKey(limit_choices_to={'role__name': 'Edző'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Edző (hívó)')),
            ],
            options={
                'verbose_name': 'Edzés Hívás',
                'verbose_name_plural': 'Edzés Hívások',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Jelenlét')),
                ('rpe_score', models.IntegerField(blank=True, null=True, verbose_name='Edzés RPE (1-10)')),
                ('placeholder_athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='assessment.placeholderathlete', verbose_name='Ideiglenes Sportoló')),
                ('registered_athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Regisztrált Sportoló')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='training_log.trainingsession', verbose_name='Edzés')),
            ],
            options={
                'verbose_name': 'Edzés Jelenlét',
                'verbose_name_plural': 'Edzés Jelenlétek',
            },
        ),
    ]
