# Generated by Django 5.2.5 on 2025-09-29 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0001_initial'),
        ('users', '0003_alter_role_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Szünet neve')),
                ('start_date', models.DateField(verbose_name='Kezdő dátum')),
                ('end_date', models.DateField(verbose_name='Befejező dátum')),
                ('category', models.CharField(choices=[('NAT', 'Nemzeti/Állami Ünnep'), ('SCH', 'Iskolai/Oktatási Szünet'), ('WNT', 'Téli Leállás'), ('SUM', 'Nyári Szünet'), ('OTH', 'Egyéb')], default='OTH', max_length=3, verbose_name='Kategória')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.club', verbose_name='Egyesület')),
            ],
            options={
                'verbose_name': 'Szünet/Leállás',
                'verbose_name_plural': 'Szünetek/Leállások',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Edzéscsoport neve (Pl. U10 fiúk)')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Hétfő'), (2, 'Kedd'), (3, 'Szerda'), (4, 'Csütörtök'), (5, 'Péntek'), (6, 'Szombat'), (7, 'Vasárnap')], verbose_name='Nap')),
                ('start_time', models.TimeField(verbose_name='Kezdés időpontja')),
                ('end_time', models.TimeField(verbose_name='Befejezés időpontja')),
                ('min_birth_year', models.IntegerField(verbose_name='Min. születési év')),
                ('max_birth_year', models.IntegerField(verbose_name='Max. születési év')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Érvényesség kezdete')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Érvényesség vége (Opcionális)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.club', verbose_name='Egyesület')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'userrole__role__name': 'Edző'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Felelős Edző')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sport', verbose_name='Sportág')),
            ],
            options={
                'verbose_name': 'Edzésrend',
                'verbose_name_plural': 'Edzésrendek',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
