# Generated by Django 5.2.5 on 2025-09-30 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0002_absenceschedule_trainingschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingschedule',
            options={'ordering': ['start_time', 'club__name'], 'verbose_name': 'Edzésrend', 'verbose_name_plural': 'Edzésrendek'},
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='max_birth_year',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='min_birth_year',
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='birth_years',
            field=models.CharField(default='', help_text='Vesszővel elválasztott születési évek.', max_length=100, verbose_name='Születési évek'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='days_of_week',
            field=models.CharField(default='', help_text='Vesszővel elválasztott napok: 1=Hétfő, 7=Vasárnap.', max_length=15, verbose_name='Napok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='genders',
            field=models.CharField(choices=[('M', 'Fiú'), ('F', 'Lány')], default='', help_text='Kiválasztott nemek (pl. F,M).', max_length=5, verbose_name='Nem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_roles__role__name': 'Edző'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Felelős Edző'),
        ),
    ]
