# Generated by Django 5.2.5 on 2025-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0003_alter_trainingschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingschedule',
            name='genders',
            field=models.CharField(help_text='Kiválasztott nemek (pl. M,F).', max_length=10, verbose_name='Nemek'),
        ),
    ]
