# Generated by Django 5.2.5 on 2025-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0004_alter_trainingschedule_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_injured',
            field=models.BooleanField(default=False),
        ),
    ]
