# Generated by Django 5.2.5 on 2025-10-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0005_attendance_is_guest_attendance_is_injured'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training_log.trainingschedule', verbose_name='Edzésrend'),
        ),
    ]
