# Generated by Django 5.2.5 on 2026-01-10 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0006_trainingsession_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-session_date', '-start_time'], 'verbose_name': 'Edzés Hívás', 'verbose_name_plural': 'Edzés Hívások'},
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='cooldown_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Levezetés'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='game_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Sport-Specific Game'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='is_warmup_playful',
            field=models.BooleanField(default=False, verbose_name='Játékos bemelegítés?'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='tactical_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Taktika'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='technical_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Technika'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='toy_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Toy (Játék)'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='warmup_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Bemelegítés'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'user_roles__role__name': 'Edző'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Edző (hívó)'),
        ),
    ]
